services:
  app:
    image: market-maker
    depends_on:
      postgres:
        condition: service_healthy
  postgres:  # <--- THIS IS THE SERVICE NAME
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=marketmaker
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d marketmaker"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s